### PR TITLE
VATIS-79: Make the profile window per drag and drop movable

### PR DESCRIPTION
**Pull request by GeheimagentNr1**
Fixes discord bug-reports:
- [VATIS-79] Can't drag profile window

### CODE REVIEW

**Comment by neilenns** [comment]
I gave this a try and it does allow the window to move, yay! The window position isn't remembered though:

1. Move the profile window
2. Open a profile
3. Close a profile

Result: The profile window is back in the middle of the main screen instead of where I put it

**Comment by GeheimagentNr1** [comment]
> I gave this a try and it does allow the window to move, yay! The window position isn't remembered though:
> 
> 1. Move the profile window
> 2. Open a profile
> 3. Close a profile
> 
> Result: The profile window is back in the middle of the main screen instead of where I put it

Fixed with the last commit

**Comment by justinshannon** [comment]
This looks great. My only recommendation is that it should also remember the position if you move the profile window and click exit. It seems to only save the window position if a profile is launched.

**Comment by GeheimagentNr1** [comment]
> This looks great. My only recommendation is that it should also remember the position if you move the profile window and click exit. It seems to only save the window position if a profile is launched.

I missed the place, where the AppConfig is loaded. So the position was saved, but not loaded.

**Pull request merged**
